SUBSTITUTIONS = {
    'a..martin@enron.com'   : 'martin-t@enron.com',
    'l..mims@enron.com'     : 'mims-p@enron.com',
    'm..love@enron.com'     : 'love-p@enron.com',
    'm..tholt@enron.com'    : 'tholt-j@enron.com',
    'd..martin@enron.com'   : 'martin-t@enron.com',
    'w..pereira@enron.com'  : 'pereira-s@enron.com',
    'l..gay@enron.com'      : 'gay-r@enron.com',
    'j..kaminski@enron.com' : 'kaminski-v@enron.com',
    'a..shankman@enron.com' : 'shankman-j@enron.com',
    'f..brawner@enron.com'  : 'brawner-s@enron.com',
    'm..smith@enron.com'    : 'None@enron.com',
    'd..steffes@enron.com'  : 'steffes-j@enron.com',
    'j..kean@enron.com'     : 'kean-s@enron.com',
    's..ward@enron.com'     : 'ward-k@enron.com',
    't..hodge@enron.com'    : 'hodge-j@enron.com',
    'e..haedicke@enron.com' : 'haedicke-m@enron.com',
    'b..sanders@enron.com'  : 'sanders-r@enron.com',
    'm..presto@enron.com'   : 'presto-k@enron.com',
    's..shively@enron.com'  : 'shively-h@enron.com',
    'm..scott@enron.com'    : 'scott-s@enron.com',
    'j..sturm@enron.com'    : 'sturm-f@enron.com',
    'j..farmer@enron.com'   : 'farmer-d@enron.com',
    'f..keavey@enron.com'   : 'keavey-p@enron.com',
    'w..delainey@enron.com' : 'delainey-d@enron.com',
    'w..white@enron.com'    : 'white-s@enron.com',
    'd..thomas@enron.com'   : 'None@enron.com',
    't..lucci@enron.com'    : 'lucci-p@enron.com',
    'm..forney@enron.com'   : 'forney-j@enron.com',
    'f..campbell@enron.com' : 'campbell-l@enron.com',
    'c..giron@enron.com'    : 'giron-d@enron.com',
    'h..lewis@enron.com'    : 'lewis-a@enron.com',
    'k..allen@enron.com'    : 'allen-p@enron.com',
}

TITLES = {
    'quenet-j'       : 'Trader',
    'dorland-c'      : 'Manager',
    'arora-h'        : 'Vice President',
    'geaccone-t'     : 'Employee',
    'haedicke-m'     : 'Managing Director Legal Department',
    'farmer-d'       : 'Manager Logistics Manager',
    'dean-c'         : 'Trader',
    'badeer-r'       : 'Director',
    'keiser-k'       : 'Employee',
    'king-j'         : 'Manager',
    'keavey-p'       : 'Employee',
    'hyatt-k'        : 'Director Pipeline Business',
    'semperger-c'    : 'Employee Senior Analyst Cash',
    'ermis-f'        : 'Director',
    'zipper-a'       : 'Vice President Enron Online',
    'taylor-m'       : 'Employee',
    'sanders-r'      : 'Vice President Enron WholeSale Services',
    'lavorato-j'     : 'CEO Enron America',
    'benson-r'       : 'Director',
    'scholtes-d'     : 'Trader',
    'causholli-m'    : 'Employee Analyst Risk Management',
    'fossum-d'       : 'Vice President',
    'allen-p'        : 'Manager',
    'hyvl-d'         : 'Employee',
    'tycholiz-b'     : 'Vice President',
    'staab-t'        : 'Employee',
    'carson-m'       : 'Manager',
    'presto-k'       : 'Vice President',
    'townsend-j'     : 'Employee',
    'schwieger-j'    : 'Trader',
    'dickson-s'      : 'Employee',
    'derrick-j'      : 'In House Lawyer',
    'baughman-d'     : 'Trader',
    'cuilla-m'       : 'Manager',
    'lokay-m'        : 'Employee Administrative Asisstant',
    'davis-d'        : 'Vice President Term',
    'shively-h'      : 'Vice President',
    'platter-p'      : 'Employee Sr.Specialist',
    'whalley-g'      : 'President',
    'symes-k'        : 'Employee',
    'martin-t'       : 'Vice President',
    'zufferli-j'     : 'Vice President',
    'ruscitti-k'     : 'Trader',
    'steffes-j'      : 'Vice President Government Affairs',
    'ring-r'         : 'Employee',
    'holst-k'        : 'Director',
    'hayslett-r'     : 'Vice President Also Chief Financial Officer and Treasurer',
    'mann-k'         : 'Employee',
    'brawner-s'      : 'Director',
    'motley-m'       : 'Director',
    'kaminski-v'     : 'Manager Risk Management Head',
    'stepenovitch-j' : 'Vice President Enery marketting and trading Florida',
    'grigsby-m'      : 'Manager',
    'swerzbin-m'     : 'Trader',
    'shapiro-r'      : 'Vice President Regulatory Affairs',
    'neal-s'         : 'Vice President',
    'kean-s'         : 'Vice President Vice President & Chief of Staff',
    'richey-c'       : 'Manager',
    'mclaughlin-e'   : 'Employee',
    'kuykendall-t'   : 'Trader',
    'mccarty-d'      : 'Vice President',
    'sager-e'        : 'Employee',
    'arnold-j'       : 'Vice President',
    'lay-k'          : 'CEO',
    'meyers-a'       : 'Employee Specialist',
    'sturm-f'        : 'Vice President',
    'pereira-s'      : 'Employee',
    'horton-s'       : 'President Enron Gas Pipeline',
    'lenhart-m'      : 'Employee',
    'lewis-a'        : 'Director',
    'beck-s'         : 'Employee Chief Operating Officer',
    'delainey-d'     : 'CEO Enron North America and Enron Enery Services',
    'may-l'          : 'Director',
    'germany-c'      : 'Employee',
    'panus-s'        : 'Employee',
    'buy-r'          : 'Manager Chief Risk Management Officer',
    'giron-d'        : 'Employee',
    'tholt-j'        : 'Vice President',
    'saibi-e'        : 'Trader',
    'maggi-m'        : 'Director',
    'lokey-t'        : 'Manager Regulatory Affairs',
    'rogers-b'       : 'Employee Associate',
    'hernandez-j'    : 'Employee Senior Specialist Logistics',
    'slinger-r'      : 'Trader',
    'forney-j'       : 'Manager Real time Trading Desk',
    'dasovich-j'     : 'Employee Government Relation Executive',
    'hodge-j'        : 'Managing Director',
    'storey-g'       : 'Director',
    'kitchen-l'      : 'President Enron Online',
    'lucci-p'        : 'Employee',
    'shankman-j'     : 'President Enron Global Mkts',
    'salisbury-h'    : 'Employee Cash Analyst',
    'donoho-l'       : 'Employee',
    'solberg-g'      : 'Employee Analyst',
    'skilling-j'     : 'CEO',
    'fischer-m'      : 'Employee',
    'mckay-b'        : 'Employee',
    'reitmeyer-j'    : 'Employee',
    'bass-e'         : 'Trader',
    'mckay-j'        : 'Director',
    'corman-s'       : 'Vice President Regulatory Affairs',
    'campbell-l'     : 'Employee Senior Specialist',
}

FULLNAMES = {
    'quenet-j'       : 'Joe Quenet',
    'dorland-c'      : 'Chris Dorland',
    'arora-h'        : 'Harpreet Arora',
    'geaccone-t'     : 'Tracy Geaccone',
    'haedicke-m'     : 'Mark Haedicke',
    'farmer-d'       : 'Daren Farmer',
    'dean-c'         : 'Craig Dean',
    'badeer-r'       : 'Robert Badeer',
    'schoolcraft-d'  : 'Darrell Schoolcraft',
    'keiser-k'       : 'Kam Keiser',
    'king-j'         : 'Jeff King',
    'keavey-p'       : 'Peter Keavey',
    'hyatt-k'        : 'Kevin Hyatt',
    'semperger-c'    : 'Cara Semperger',
    'ermis-f'        : 'Frank Ermis',
    'jones-t'        : 'Tana Jones',
    'zipper-a'       : 'Andy Zipper',
    'taylor-m'       : 'Mark Taylor',
    'sanders-r'      : 'Richard Sanders',
    'lavorato-j'     : 'John Lavorato',
    'benson-r'       : 'Robert Benson',
    'donohoe-t'      : 'Tom Donohoe',
    'scholtes-d'     : 'Diana Scholtes',
    'causholli-m'    : 'Monika Causholli',
    'pimenov-v'      : 'Vladi Pimenov',
    'fossum-d'       : 'Drew Fossum',
    'allen-p'        : 'Philip Allen',
    'blair-l'        : 'Lynn Blair',
    'tycholiz-b'     : 'Barry Tycholiz',
    'weldon-c'       : 'Charles Weldon',
    'ward-k'         : 'Kim Ward',
    'presto-k'       : 'Kevin Presto',
    'townsend-j'     : 'Judy Townsend',
    'schwieger-j'    : 'Jim Schwieger',
    'heard-m'        : 'Marie Heard',
    'dickson-s'      : 'Stacy Dickson',
    'buy-r'          : 'Rick Buy',
    'baughman-d'     : 'Don Baughman',
    'rapp-b'         : 'Bill Rapp',
    'cuilla-m'       : 'Martin Cuilla',
    'parks-j'        : 'Joe Parks',
    'davis-d'        : 'Dana Davis',
    'shively-h'      : 'Hunter Shively',
    'love-p'         : 'Phillip Love',
    'platter-p'      : 'Phillip Platter',
    'whalley-g'      : 'Greg Whalley',
    'symes-k'        : 'Kate Symes',
    'wolfe-j'        : 'Jason Wolfe',
    'ring-a'         : 'Andrea Ring',
    'martin-t'       : 'Thomas Martin',
    'zufferli-j'     : 'John Zufferli',
    'ruscitti-k'     : 'Kevin Ruscitti',
    'steffes-j'      : 'James Steffes',
    'ring-r'         : 'Richard Ring',
    'kean-s'         : 'Steven Kean',
    'nemec-g'        : 'Gerald Nemec',
    'staab-t'        : 'Theresa Staab',
    'hayslett-r'     : 'Rod Hayslett',
    'mann-k'         : 'Kay Mann',
    'cash-m'         : 'Michelle Cash',
    'brawner-s'      : 'Sandra Brawner',
    'scott-s'        : 'Susan Scott',
    'motley-m'       : 'Matthew Motley',
    'hyvl-d'         : 'Dan Hyvl',
    'kaminski-v'     : 'Vince Kaminski',
    'stepenovitch-j' : 'Joe Stepenovitch',
    'grigsby-m'      : 'Michael Grigsby',
    'swerzbin-m'     : 'Mike Swerzbin',
    'shapiro-r'      : 'Richard Shapiro',
    'neal-s'         : 'Scott Neal',
    'holst-k'        : 'Keith Holst',
    'richey-c'       : 'Cooper Richey',
    'mclaughlin-e'   : 'Errol McLaughlin',
    'kuykendall-t'   : 'Tori Kuykendall',
    'mccarty-d'      : 'Danny McCarty',
    'sager-e'        : 'Elizabeth Sager',
    'arnold-j'       : 'John Arnold',
    'lay-k'          : 'Kenneth Lay',
    'meyers-a'       : 'Albert Meyers',
    'sturm-f'        : 'Fletcher Sturm',
    'carson-m'       : 'Mike Carson',
    'horton-s'       : 'Stanley Horton',
    'lenhart-m'      : 'Matthew Lenhart',
    'lewis-a'        : 'Andrew Lewis',
    'beck-s'         : 'Sally Beck',
    'kitchen-l'      : 'Louise Kitchen',
    'may-l'          : 'Lawrence May',
    'germany-c'      : 'Chris Germany',
    'whitt-m'        : 'Mark Whitt',
    'panus-s'        : 'Stephanie Panus',
    'derrick-j'      : 'James Derrick',
    'giron-d'        : 'Daron Giron',
    'tholt-j'        : 'Jane Tholt',
    'saibi-e'        : 'Eric Saibi',
    'maggi-m'        : 'Michael Maggi',
    'white-s'        : 'Stacey White',
    'lokey-t'        : 'Teb Lokey',
    'rogers-b'       : 'Benjamin Rogers',
    'gay-r'          : 'Randall Gay',
    'hernandez-j'    : 'Juan Hernandez',
    'slinger-r'      : 'Ryan Slinger',
    'forney-j'       : 'John Forney',
    'dasovich-j'     : 'Jeff Dasovich',
    'hodge-j'        : 'John Hodge',
    'storey-g'       : 'Geoffery Storey',
    'delainey-d'     : 'David Delainey',
    'lucci-p'        : 'Paul Lucci',
    'shankman-j'     : 'Jeffrey Shankman',
    'salisbury-h'    : 'Holden Salisbury',
    'donoho-l'       : 'Lindy Donoho',
    'mims-p'         : 'Patrice Mims',
    'watson-k'       : 'Kimberly Watson',
    'solberg-g'      : 'Geir Solberg',
    'skilling-j'     : 'Jeffery Skilling',
    'thomas-p'       : 'Paul Thomas',
    'pereira-s'      : 'Susan Pereira',
    'fischer-m'      : 'Mary Fischer',
    'mckay-b'        : 'Bradley Mckay',
    'reitmeyer-j'    : 'Jay Reitmeyer',
    'bass-e'         : 'Eric Bass',
    'mckay-j'        : 'Jonathan Mckay',
    'corman-s'       : 'Shelley Corman',
    'campbell-l'     : 'Larry Campbell',
    'lokay-m'        : 'Michelle Lokay',
    'bailey-s'       : 'Susan Bailey',
}
